### ISSUE TITLE
Command based healthchecks

### ISSUE THREAD

**Issue by IgnisDa** [dokku/docker-container-healthchecker#91]
### Description of feature

Looking at options in https://dokku.com/docs/deployment/zero-downtime-deploys/#customizing-checks, I think commands are not allowed as healthchecks.

I am using an image that has a command `is_ready` (much like `pg_isready`) that returns a non-zero exit status if the service is not ready. I would like to use this instead of a web based check for my service.

**Comment by josegonzalez** [comment]
Commands are allowed in healthchecks under 0.31.x. The example only shows a simple web check.

Docs might be wrong though, seems it should be a list: https://github.com/dokku/docker-container-healthchecker/blob/master/tests/fixtures/app.json#L25-L27

**Comment by IgnisDa** [comment]
Unrelated, but is it possible to get the output of a command based healthcheck?

**Comment by josegonzalez** [comment]
Output is only shown on error.

**Comment by IgnisDa** [comment]
Its not for me
![image](https://github.com/dokku/docker-container-healthchecker/assets/60938164/3a3161b8-6d13-45b8-8dff-6c874c68ffa6)

using version `0.6.4`.

**Comment by josegonzalez** [comment]
Mind filing a bug for that?
